print('number of train samples')
print(len(os.listdir('../input/datatree/train/nv')))
print(len(os.listdir('../input/datatree/train/mel')))
print(len(os.listdir('../input/datatree/train/bkl')))
print(len(os.listdir('../input/datatree/train/bcc')))
print(len(os.listdir('../input/datatree/train/akiec')))
print(len(os.listdir('../input/datatree/train/vasc')))
print(len(os.listdir('../input/datatree/train/df')))
print(len(os.listdir('../input/datatree/train/nod')))
